server:
  port: 8189
  servlet:
    context-path: /wannago
spring:
  application:
    name: WannaGo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 526207653680-ur5damesp4j96hafkfjcja7tsm32drds.apps.googleusercontent.com
            client-secret: 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

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: audit
    default-schema: public
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://5.188.140.199:5432/postgres
    username: postgres
    password: 123456Vv
    driver-class-name: org.postgresql.Driver

openapi:
  security:
    scheme:
      name: default
  version: 1

aws:
  accessKeyId: pZHFL6TARutSLZ1E7f2Tgn
  secret: 8PdV8sEkmeK13DRSM8g3WL5i7wv8Qg4hVMdSvrupSxrP
  bucket: wannago