server:
  port: 8189
  servlet:
    context-path: /wannago
spring:
  h2:
    console:
      path: /h2
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: audit
    default-schema: public
  jpa:
    database: h2
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver